version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: './log/logging.log'
    encoding: 'utf-8'
loggers:
  default:
    level: DEBUG
    handlers: [console,file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]